import Foundation

extension CGFloat {

  static var point0_45: CGFloat { return 0.45 }
  static var point0: CGFloat { return 0 }
  static var point1: CGFloat { return 1 }
  static var point2: CGFloat { return 2 }
  static var point3: CGFloat { return 3 }
  static var point4: CGFloat { return 4 }
  static var point5: CGFloat { return 5 }
  static var point6: CGFloat { return 6 }
  static var point7: CGFloat { return 7 }
  static var point8: CGFloat { return 8 }
  static var point9: CGFloat { return 9 }
  static var point10: CGFloat { return 10 }
  static var point11: CGFloat { return 11 }
  static var point12: CGFloat { return 12 }
  static var point13: CGFloat { return 13 }
  static var point14: CGFloat { return 14 }
  static var point15: CGFloat { return 15 }
  static var point16: CGFloat { return 16 }
  static var point17: CGFloat { return 17 }
  static var point18: CGFloat { return 18 }
  static var point19: CGFloat { return 19 }
  static var point20: CGFloat { return 20 }
  static var point21: CGFloat { return 21 }
  static var point22: CGFloat { return 22 }
  static var point23: CGFloat { return 23 }
  static var point24: CGFloat { return 24 }
  static var point25: CGFloat { return 25 }
  static var point26: CGFloat { return 26 }
  static var point27: CGFloat { return 27 }
  static var point28: CGFloat { return 28 }
  static var point29: CGFloat { return 29 }
  static var point30: CGFloat { return 30 }
  static var point32: CGFloat { return 32 }
  static var point34: CGFloat { return 34 }
  static var point36: CGFloat { return 36 }
  static var point40: CGFloat { return 40 }
  static var point42: CGFloat { return 42 }
  static var point43: CGFloat { return 43 }
  static var point44: CGFloat { return 44 }
  static var point45: CGFloat { return 45 }
  static var point47: CGFloat { return 47 }
  static var point48: CGFloat { return 48 }
  static var point49: CGFloat { return 49 }
  static var point50: CGFloat { return 50 }
  static var point52: CGFloat { return 52 }
  static var point53: CGFloat { return 53 }
  static var point54: CGFloat { return 54 }
  static var point55: CGFloat { return 55 }
  static var point56: CGFloat { return 56 }
  static var point58: CGFloat { return 58 }
  static var point60: CGFloat { return 60 }
  static var point62: CGFloat { return 62 }
  static var point63: CGFloat { return 63 }
  static var point70: CGFloat { return 70 }
  static var point72: CGFloat { return 72 }
  static var point76: CGFloat { return 76 }
  static var point78: CGFloat { return 78 }
  static var point79: CGFloat { return 79 }
  static var point80: CGFloat { return 80 }
  static var point84: CGFloat { return 84 }
  static var point86: CGFloat { return 86 }
  static var point87: CGFloat { return 87 }
  static var point90: CGFloat { return 90 }
  static var point95: CGFloat { return 95 }
  static var point96: CGFloat { return 96 }
  static var point100: CGFloat { return 100 }
  static var point300: CGFloat { return 300 }
}
